{
  "dataset_name": "ChaosNLI",
  "upstream_repo": "https://github.com/easonnie/ChaosNLI.git",
  "files": {
    "snli": {
      "filename": "chaosNLI_snli.jsonl",
      "path": "data\\chaosnli\\raw\\chaosNLI_snli.jsonl",
      "sha256": "99f9015ddda7d85f66a087452bc30d53974314fe27e7d589e2f41ad44bd509c1",
      "size_bytes": 768107,
      "row_count": 1514,
      "acquired_at_utc": "2026-08-02T04:07:34.091575+00:00"
    },
    "mnli": {
      "filename": "chaosNLI_mnli_m.jsonl",
      "path": "data\\chaosnli\\raw\\chaosNLI_mnli_m.jsonl",
      "sha256": "8eb49b589488e7b1a9ec95fb8a864bd50f0509b4f808eed0aed3f8167617664d",
      "size_bytes": 871731,
      "row_count": 1599,
      "acquired_at_utc": "2026-08-02T04:07:34.102077+00:00"
    },
    "alphanli": {
      "filename": "chaosNLI_alphanli.jsonl",
      "path": "data\\chaosnli\\raw\\chaosNLI_alphanli.jsonl",
      "sha256": "f55817ecc11a02ba3030cd7d2c567d23843456809020723abad53f4fde024c9e",
      "size_bytes": 793550,
      "row_count": 1532,
      "acquired_at_utc": "2026-08-02T04:07:34.113033+00:00"
    }
  }
}